version: '3.8'

# 定義服務
services:
  mongodb: # 定義一個mongodb的服務
    image: mongo:latest # 拉取指定版本的mongo的image
    container_name: ${MONGO_IP} # 設定容器名稱，這個名稱用於容器之間的網絡通信
    restart: always # 配置容器在任何情况下都重新启动，包括容器退出时
    ports:
      - "${MONGO_PORT}:27017" # 主機端口:容器端口
    environment: # 添加賬密
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongodb_db:/data/db # 引用定義好的卷名:容器中目錄 <也可直接用資料夾路徑：/data/db>

  redis:
    image: redis:latest
    container_name: ${REDIS_IP}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis_db:/data 

  flask_app:
    build: . # 告訴docker-compose，從當前目錄下找Dockerfile文件構建鏡像
    container_name: ${FLASK_NAME}
    restart: always
    ports:
      - "${FLASK_PORT}:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app # 主机目录:容器目录，進入到當下的代碼目錄，用點來代替當前路徑就好了，掛在到容器上的/app目錄下
